# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink: /:title/

# Setup
title:            Alice Wang
tagline:          'Notes'
description:      'Mathematics, programming and finance'
url:              http://aliciawyy.github.io
baseurl:          /

author:
  name:           'Alice Wang'
  url:             
  email: alicia.wang12@gmail.com
  # URL of your avatar or profile pic (you could use your GitHub profile pic)
  avatar: https://avatars2.githubusercontent.com/u/6472721?v=3&s=460

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           http://aliciawyy.github.io
  
# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: alicia.wang12@gmail.com
  facebook:
  flickr:
  github: aliciawyy
  instagram:
  linkedin: aliciaywang
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: 
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus:

gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed
  - jekyll-paginate
